server:
  port: 8082

spring:
  application:
    name: movie-service
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviedb
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
dev:
  mode: true

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: mongodb://mongodb:27017/moviedb
    redis:
      host: redis
      port: 6379
dev:
  mode: false
