server:
  port: 8082

spring:
  application:
    name: movie-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/moviedb
    redis:
      host: localhost
      port: 6379
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

# For local development with no DB running
dev:
  mode: true
